INSERT INTO superheroes (nombre) VALUES('Ant-Man');
INSERT INTO superheroes (nombre) VALUES('Aquaman');
INSERT INTO superheroes (nombre) VALUES('Asterix');
INSERT INTO superheroes (nombre) VALUES('The Atom');
INSERT INTO superheroes (nombre) VALUES('The Avengers');
INSERT INTO superheroes (nombre) VALUES('Batgirl');
INSERT INTO superheroes (nombre) VALUES('Batman');
INSERT INTO superheroes (nombre) VALUES('Batwoman');
INSERT INTO superheroes (nombre) VALUES('Black Canary');
INSERT INTO superheroes (nombre) VALUES('Black Panther');
INSERT INTO superheroes (nombre) VALUES('Captain America');
INSERT INTO superheroes (nombre) VALUES('Captain Marvel');
INSERT INTO superheroes (nombre) VALUES('Catwoman');
INSERT INTO superheroes (nombre) VALUES('Conan the Barbarian');
INSERT INTO superheroes (nombre) VALUES('Daredevil');
INSERT INTO superheroes (nombre) VALUES('The Defenders');
INSERT INTO superheroes (nombre) VALUES('Doc Savage');
INSERT INTO superheroes (nombre) VALUES('Doctor Strange');
INSERT INTO superheroes (nombre) VALUES('Elektra');
INSERT INTO superheroes (nombre) VALUES('Fantastic Four');
INSERT INTO superheroes (nombre) VALUES('Ghost Rider');
INSERT INTO superheroes (nombre) VALUES('Green Arrow');
INSERT INTO superheroes (nombre) VALUES('Green Lantern');
INSERT INTO superheroes (nombre) VALUES('Guardians of the Galaxy');
INSERT INTO superheroes (nombre) VALUES('Hawkeye');
INSERT INTO superheroes (nombre) VALUES('Hellboy');
INSERT INTO superheroes (nombre) VALUES('Incredible Hulk');
INSERT INTO superheroes (nombre) VALUES('Iron Fist');
INSERT INTO superheroes (nombre) VALUES('Iron Man');
INSERT INTO superheroes (nombre) VALUES('Marvelman');
INSERT INTO superheroes (nombre) VALUES('Robin');
INSERT INTO superheroes (nombre) VALUES('The Rocketeer');
INSERT INTO superheroes (nombre) VALUES('The Shadow');
INSERT INTO superheroes (nombre) VALUES('Spider-Man');
INSERT INTO superheroes (nombre) VALUES('Sub-Mariner');
INSERT INTO superheroes (nombre) VALUES('Supergirl');
INSERT INTO superheroes (nombre) VALUES('Superman');
INSERT INTO superheroes (nombre) VALUES('Teenage Mutant Ninja Turtles');
INSERT INTO superheroes (nombre) VALUES('Thor');
INSERT INTO superheroes (nombre) VALUES('The Wasp');
INSERT INTO superheroes (nombre) VALUES('Watchmen');
INSERT INTO superheroes (nombre) VALUES('Wolverine');
INSERT INTO superheroes (nombre) VALUES('Wonder Woman');
INSERT INTO superheroes (nombre) VALUES('X-Men');
INSERT INTO superheroes (nombre) VALUES('Zatanna');
INSERT INTO superheroes (nombre) VALUES('Zatara');